apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-prod

resources:
  - namespace.yaml
  - ../../base

images:
  - name: k8s-fastapi-kustomize
    newTag: prod

patches:
  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: ConfigMap
      name: api-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: prod
  - target:
      kind: HorizontalPodAutoscaler
      name: api
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 10
