apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: fastapi-demo
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - port: 80
      targetPort: http
      name: http
