apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-dev

resources:
  - namespace.yaml
  - ../../base

# Em dev rodamos 1 replica e removemos o HPA
# (o metrics-server nao vem instalado no kind por padrao).
patches:
  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: ConfigMap
      name: api-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: dev
  - target:
      kind: HorizontalPodAutoscaler
      name: api
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: api
